### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by HaukeCornell** [fepegar/gestures-miccai-2021#1]
Best Fernando, 
thanks for providing this repository alongside the feature dataset and the paper. This is essential work!

I have run into a few issues replicating it, though.
What specific anaconda version were you using? I had to add protobuf~=3.19.0 and pillow<7 to the requirements to get your code to execute. Also, I created the slack.json for sacred and changed a few file paths in your code.  However, it still fails on: train_features_lstm  failed after 3 seconds  with AttributeError: 'DataFrame' object has no attribute 'RatioGTCS'.

**Comment by fepegar** [comment]
Hi, @HaukeCornell. I'm glad you find this research useful!

I'm afraid the code is not fully reproducible as I'm not allowed to share the data. You can, however, adapt the code to your own needs.

I used a CSV file containing one row per seizure. The `Duration` column was the seizure duration in seconds. `RatioGTCS` is a number between 0 and 1 representing how far into the seizure the patient starts convulsing. I hope that helps!
