### ISSUE TITLE
slack_config_path = Path('~/slack.json').expanduser()

### ISSUE THREAD

**Issue by myx20001015** [fepegar/gestures-miccai-2021#4]
slack_config_path = Path('~/slack.json').expanduser()
FileNotFoundError: [Errno 2] No such file or directory: '/root/slack.json'
I cannot find this file in your code. Could you provide it? Thank you.

**Comment by fepegar** [comment]
Hi, @myx20001015. I've removed the corresponding lines from the script.

**Comment by myx20001015** [comment]
So I should delete the relevant command, right?

**Comment by myx20001015** [comment]
Can you provide the script? thank you.

**Comment by fepegar** [comment]
It's updated on the main branch, so you can just `git pull`

https://github.com/fepegar/gestures-miccai-2021/commit/b9792400f27c57f622f5975b66832bf3e1b7ab17
